config/routes.rb
Rails.application.routes.draw do
  get 'print/sale_lists_print'
  get 'print/sale_lists_slip/:id', to: 'print#sale_lists_slip', as: 'sale_lists_slip'
  resources :debt_capitals
  resources :product_sale_lists
  resources :general_expenses
  resources :capitals
  resources :accounts
  resources :expenses
  resources :incomes
  resources :payment_modes
  resources :expense_categories
  get 'settings/index', :as => :settings
  get 'settings/edit_language', :as => :edit_language
  patch 'language/:id', to: 'settings#update_language', :as => :update_language
  get 'reports/index', :as => :reports
  resources :sale_lists do
    member do
      get :add_images
      delete :delete_image_attachment
    end
  end
  post '/sale_lists/:id/add_images', to: 'sale_lists#update_images', :as => :update_images_sale_list
  resources :customers
  resources :product_sales
  post 'product_sales/checkout/', to: 'product_sales#checkout'
  resources :business_types
  get '/business_types/:id/add', to: 'business_types#add', :as => :add_business_type
  resources :categories
  resources :roles
  get 'role/permission/:id', to: 'roles#permission', as: 'permission'
  post 'role/permission/:id/create_permission', to: 'roles#create_permission', as: 'create_permission'
  resources :themes
  get '/user_theme/:id', to: 'themes#update_user_theme', :as => :user_theme
  resources :pages
  devise_for :users
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/payment_mode.rb
class PaymentMode < ApplicationRecord
    validates :name, presence: true

    has_many :incomes
    has_many :expenses
end

app/controllers/payment_modes_controller.rb
class PaymentModesController < Admin::AdminTemplateController
  before_action :set_payment_mode, only: [:show, :edit, :update, :destroy]

  # GET /payment_modes
  # GET /payment_modes.json
  def index
    @title = 'Payment Modes'
    @payment_modes = PaymentMode.where(created_by: current_user.id).or(PaymentMode.where(created_by: nil))
  end

  # GET /payment_modes/1
  # GET /payment_modes/1.json
  def show
    @title = 'Payment Modes'
  end

  # GET /payment_modes/new
  def new
    @title = 'Payment Modes'
    @payment_mode = PaymentMode.new
  end

  # GET /payment_modes/1/edit
  def edit
    @title = 'Payment Modes'
  end

  # POST /payment_modes
  # POST /payment_modes.json
  def create
    @title = 'Payment Modes'
    @payment_mode = PaymentMode.new(payment_mode_params)
    @payment_mode.created_by = current_user.id

    respond_to do |format|
      if @payment_mode.save
        format.html { redirect_to payment_modes_path, notice: 'Payment mode was successfully created.' }
        format.json { render :show, status: :created, location: @payment_mode }
      else
        format.html { render :new }
        format.json { render json: @payment_mode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payment_modes/1
  # PATCH/PUT /payment_modes/1.json
  def update
    @title = 'Payment Modes'
    @payment_mode.created_by = current_user.id
    respond_to do |format|
      if @payment_mode.update(payment_mode_params)
        format.html { redirect_to payment_modes_path, notice: 'Payment mode was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment_mode }
      else
        format.html { render :edit }
        format.json { render json: @payment_mode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_modes/1
  # DELETE /payment_modes/1.json
  def destroy
    @payment_mode.destroy
    respond_to do |format|
      format.html { redirect_to payment_modes_url, notice: 'Payment mode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_mode
      @payment_mode = PaymentMode.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def payment_mode_params
      params.require(:payment_mode).permit(:name)
    end
end

app/helpers/payment_modes_helper.rb
module PaymentModesHelper
end

app/views/payment_modes/_form.html.erb
<%= form_with(model: payment_mode, local: true) do |form| %>
  <% if payment_mode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment_mode.errors.count, "error") %> prohibited this payment_mode from being saved:</h2>

      <ul>
        <% payment_mode.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <span class="badge badge-danger"><%= t('form_action.required') %></span>
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control", placeholder: true %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-info" %>
    <%= link_to 'Cancel', payment_modes_path, class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/payment_modes/edit.html.erb
<div class="row">
    <div class="col-md-8">
        <%= render 'form', payment_mode: @payment_mode %>
    </div>
</div>

app/views/payment_modes/index.html.erb
<%= link_to 'New Payment Mode', new_payment_mode_path, class: "btn btn-info" %>
<table class="table table-striped mt-3">
  <thead class="text-white bg-secondary">
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @payment_modes.each do |payment_mode| %>
      <tr>
        <td><%= payment_mode.name %></td>
        <td>
          <%= link_to '<i class="fas fa-info-circle"></i>'.html_safe, payment_mode, data: { toggle: 'tooltip', placement: 'bottom' }, title: t("action_button.permission") %>
          <% if payment_mode.created_by == nil %>
            <%= link_to '<i class="fas fa-edit"></i>'.html_safe, "javascript:void(0)", class: "icon_disabled" %>
          <% else %>
            <%= link_to '<i class="fas fa-edit"></i>'.html_safe, edit_payment_mode_path(payment_mode) %>
          <% end %>
          <% if payment_mode.incomes.count > 0 || payment_mode.expenses.count > 0 || payment_mode.created_by == nil %>
            <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, "javascript:void(0)", class: "icon_disabled" %>
          <% else %>
            <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, payment_mode, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
    <% if @payment_modes.count < 1 %>
      <tr>
        <td colspan="4" class="text-center">Empty Datas</td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/payment_modes/new.html.erb
<div class="row">
    <div class="col-md-8">
        <%= render 'form', payment_mode: @payment_mode %>
    </div>
</div>

app/views/payment_modes/show.html.erb
<table class="mb-3">
  <tr>
    <th>Name:</th>
    <td><%= @payment_mode.name %></td>
  </tr>
</table>
<%= link_to 'Edit', edit_payment_mode_path(@payment_mode), class: "btn btn-info" %>
<%= link_to 'Back', payment_modes_path, class: "btn btn-secondary" %>