config/routes.rb
Rails.application.routes.draw do
  get 'print/sale_lists_print'
  get 'print/sale_lists_slip/:id', to: 'print#sale_lists_slip', as: 'sale_lists_slip'
  resources :debt_capitals
  resources :product_sale_lists
  resources :general_expenses
  resources :capitals
  resources :accounts
  resources :expenses
  resources :incomes
  resources :payment_modes
  resources :expense_categories
  get 'settings/index', :as => :settings
  get 'settings/edit_language', :as => :edit_language
  patch 'language/:id', to: 'settings#update_language', :as => :update_language
  get 'reports/index', :as => :reports
  resources :sale_lists do
    member do
      get :add_images
      delete :delete_image_attachment
    end
  end
  post '/sale_lists/:id/add_images', to: 'sale_lists#update_images', :as => :update_images_sale_list
  resources :customers
  resources :product_sales
  post 'product_sales/checkout/', to: 'product_sales#checkout'
  resources :business_types
  get '/business_types/:id/add', to: 'business_types#add', :as => :add_business_type
  resources :categories
  resources :roles
  get 'role/permission/:id', to: 'roles#permission', as: 'permission'
  post 'role/permission/:id/create_permission', to: 'roles#create_permission', as: 'create_permission'
  resources :themes
  get '/user_theme/:id', to: 'themes#update_user_theme', :as => :user_theme
  resources :pages
  devise_for :users
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/debt_capital.rb
class DebtCapital < ApplicationRecord
  include Filterable

  validates :date, presence: true
  validates :category_id, presence: true
  validates :amount, presence: true

  belongs_to :category

  scope :filter_by_category_id, -> (category_id) { where category_id: category_id }
  scope :filter_by_note, -> (note) { where("note LIKE ?", "%#{note}%")}
end

app/controllers/debt_capitals_controller.rb
class DebtCapitalsController < Admin::AdminTemplateController
  before_action :set_debt_capital, only: [:show, :edit, :update, :destroy]
  before_action :set_title, only: [:index, :new, :create, :show, :edit, :update]

  # GET /debt_capitals
  # GET /debt_capitals.json
  def index
    @categories = Category.where(created_by: current_user.id)
    @debt_capitals = DebtCapital.filter(params.slice(:category_id, :note))
    @debt_capitals = @debt_capitals.where(created_by: current_user.id).order(date: :desc)
  end

  # GET /debt_capitals/1
  # GET /debt_capitals/1.json
  def show
  end

  # GET /debt_capitals/new
  def new
    @debt_capital = DebtCapital.new
  end

  # GET /debt_capitals/1/edit
  def edit
  end

  # POST /debt_capitals
  # POST /debt_capitals.json
  def create
    @debt_capital = DebtCapital.new(debt_capital_params)
    @debt_capital.created_by = current_user.id

    respond_to do |format|
      if @debt_capital.save
        format.html { redirect_to debt_capitals_path, notice: 'Debt capital was successfully created.' }
        format.json { render :show, status: :created, location: @debt_capital }
      else
        format.html { render :new }
        format.json { render json: @debt_capital.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /debt_capitals/1
  # PATCH/PUT /debt_capitals/1.json
  def update
    @debt_capital.updated_by = current_user.id
    respond_to do |format|
      if @debt_capital.update(debt_capital_params)
        format.html { redirect_to debt_capitals_path, notice: 'Debt capital was successfully updated.' }
        format.json { render :show, status: :ok, location: @debt_capital }
      else
        format.html { render :edit }
        format.json { render json: @debt_capital.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /debt_capitals/1
  # DELETE /debt_capitals/1.json
  def destroy
    @debt_capital.destroy
    respond_to do |format|
      format.html { redirect_to debt_capitals_url, notice: 'Debt capital was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_debt_capital
      @debt_capital = DebtCapital.find(params[:id])
    end

    def set_title
      @title = t("menu_title.business.debt_capital." + params[:action])
    end

    # Only allow a list of trusted parameters through.
    def debt_capital_params
      params.require(:debt_capital).permit(:date, :category_id, :amount, :note)
    end
end

app/helpers/debt_capitals_helper.rb
module DebtCapitalsHelper
    def debt_capital
        DebtCapital.where(created_by: current_user.id).sum("amount")
    end

    def debt_capital_with_category(category)
        DebtCapital.where(created_by: current_user.id, category: category).sum("amount")
    end
end

app/views/debt_capitals/_form.html.erb
<%= form_with(model: debt_capital, local: true) do |form| %>
  <% if debt_capital.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(debt_capital.errors.count, "error") %> prohibited this debt_capital from being saved:</h2>

      <ul>
        <% debt_capital.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <span class="badge badge-danger"><%= t('form_action.required') %></span>
    <%= form.label :date %>
    <%= form.text_field :date, data: { behavior: "flatpickr" }, class: "form-control bg-white", placeholder: true %>
  </div>

  <div class="form-group">
    <span class="badge badge-danger"><%= t('form_action.required') %></span>
    <%= form.label :category_id %>
    <%= form.select(:category_id, Category.where(created_by: current_user.id).collect {|category| [category.name, category.id]}, {:prompt => t('form_action.select_category')}, { :class => 'form-control select2' }) %>
  </div>

  <div class="form-group">
    <span class="badge badge-danger"><%= t('form_action.required') %></span>
    <%= form.label :amount %>
    <%= form.number_field :amount, class: "form-control", placeholder: true %>
  </div>

  <div class="form-group">
    <%= form.label :note %>
    <%= form.text_area :note, class: "form-control", placeholder: true %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-info" %>
    <%= link_to 'Cancel', debt_capitals_path, class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/debt_capitals/_index_header.html.erb
<nav class="navbar navbar-index-header">
  <%= link_to 'New debt capital', new_debt_capital_path, class: "btn btn-info" %>
  <%= form_tag debt_capitals_path, method: "get", class: "form-inline" do %>
    <%= select_tag "category_id", options_from_collection_for_select(@categories, "id", "name", selected: params[:category_id]), prompt: "Select a category", class: "form-control select2" %>
    <div class="input-group ml-md-2">
      <%= text_field_tag :note, params[:note], placeholder: "note", class: "form-control" %>
      <div class="input-group-append">
        <%= button_tag(type: "submit", class: "btn btn-outline-secondary", id: "search-submit") do %>
          <i class="fas fa-search"></i>
        <% end %>
      </div>
    </div>
  <% end %>
</nav>


<script>
  $("#category_id").change(function() {
    $("#search-submit").click();
  });
</script>

app/views/debt_capitals/edit.html.erb
<div class="row">
    <div class="col-md-8">
        <%= render 'form', debt_capital: @debt_capital %>
    </div>
</div>

app/views/debt_capitals/index.html.erb
<%= render 'index_header' %>
<div class="table-responsive">
  <table class="table table-striped mt-3">
    <thead class="text-white bg-secondary">
      <tr>
        <th>Date</th>
        <th>Category</th>
        <th class="text-right">Amount</th>
        <th>Note</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @debt_capitals.each do |debt_capital| %>
        <tr>
          <td><%= debt_capital.date.strftime("%d-%m-%Y") %></td>
          <td><%= debt_capital.category.name %></td>
          <td class="text-right"><%= debt_capital.amount %></td>
          <td><%= debt_capital.note %></td>
          <td>
            <%= link_to '<i class="fas fa-info-circle"></i>'.html_safe, debt_capital, data: { toggle: 'tooltip', placement: 'bottom' }, title: t("action_button.detail") %>
            <%= link_to '<i class="fas fa-edit"></i>'.html_safe, edit_debt_capital_path(debt_capital), data: { toggle: 'tooltip', placement: 'bottom' }, title: t("action_button.edit") %>
            <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, debt_capital, method: :delete, data: { confirm: 'Are you sure?', toggle: 'tooltip', placement: 'bottom' }, title: t("action_button.delete") %>
          </td>
        </tr>
      <% end %>
      <% if @debt_capitals.count < 1 %>
        <tr>
          <td colspan="5" class="text-center">Empty Datas</td>
        </tr>
      <% else %>
        <tr class="bg-secondary text-white">
          <td colspan="2" class="text-center">Total Amount</td>
          <td class="text-right"><%= @debt_capitals.map(&:amount).sum %></td>
          <td colspan="2"></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/debt_capitals/new.html.erb
<div class="row">
    <div class="col-md-8">
        <%= render 'form', debt_capital: @debt_capital %>
    </div>
</div>

app/views/debt_capitals/show.html.erb
<table class="show-table">
  <tr>
    <th>Date:</th>
    <td><%= @debt_capital.date.strftime("%d-%m-%Y") %></td>
  </tr>
  <tr>
    <th>Category:</th>
    <td><%= @debt_capital.category.name %></td>
  </tr>
  <tr>
    <th>Amount:</th>
    <td><%= @debt_capital.amount %></td>
  </tr>
  <tr>
    <th>Note:</th>
    <td><%= @debt_capital.note %></td>
  </tr>
</table>
<%= link_to 'Edit', edit_debt_capital_path(@debt_capital), class: "btn btn-info" %>
<%= link_to 'Back', debt_capitals_path, class: "btn btn-secondary" %>