config/routes.rb
Rails.application.routes.draw do
  get 'print/sale_lists_print'
  get 'print/sale_lists_slip/:id', to: 'print#sale_lists_slip', as: 'sale_lists_slip'
  resources :debt_capitals
  resources :product_sale_lists
  resources :general_expenses
  resources :capitals
  resources :accounts
  resources :expenses
  resources :incomes
  resources :payment_modes
  resources :expense_categories
  get 'settings/index', :as => :settings
  get 'settings/edit_language', :as => :edit_language
  patch 'language/:id', to: 'settings#update_language', :as => :update_language
  get 'reports/index', :as => :reports
  resources :sale_lists do
    member do
      get :add_images
      delete :delete_image_attachment
    end
  end
  post '/sale_lists/:id/add_images', to: 'sale_lists#update_images', :as => :update_images_sale_list
  resources :customers
  resources :product_sales
  post 'product_sales/checkout/', to: 'product_sales#checkout'
  resources :business_types
  get '/business_types/:id/add', to: 'business_types#add', :as => :add_business_type
  resources :categories
  resources :roles
  get 'role/permission/:id', to: 'roles#permission', as: 'permission'
  post 'role/permission/:id/create_permission', to: 'roles#create_permission', as: 'create_permission'
  resources :themes
  get '/user_theme/:id', to: 'themes#update_user_theme', :as => :user_theme
  resources :pages
  devise_for :users
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/sale_list.rb
class SaleList < ApplicationRecord
  include Filterable

  paginates_per 25

  belongs_to :customer
  has_many_attached :avatars

  scope :filter_by_customer_id, -> (customer_id) { where customer_id: customer_id }
  scope :filter_by_product_id, -> (product_id) do
    ids = SaleListBusinessType.where(business_type_id: product_id).distinct.pluck(:sale_list_id)
    where(id: ids)
  end
  scope :filter_by_debt, -> (debt) { where(debt: true)}
  scope :filter_by_start_date, -> (date) { where "date >= (?)", DateTime.parse(date).beginning_of_day }
  scope :filter_by_end_date, -> (date) { where "date <= (?)", DateTime.parse(date).end_of_day }
  scope :filter_by_note, -> (note) { where("note LIKE ?", "%#{note}%")}

  scope :for_date_range, -> (start_date, end_date) do
    where(date: start_date.beginning_of_day..end_date.end_of_day)
  end

  scope :count_by_date, -> () do
    group('date(date)').count
  end
end

app/controllers/sale_lists_controller.rb
class SaleListsController < Admin::AdminTemplateController
  before_action :set_sale_list, only: [:show, :edit, :update, :update_images, :destroy]

  def index
    @title = t("menu_title.business.sale_list.index")
    @customers = Customer.where(created_by: current_user).order("name ASC")
    @products = BusinessType.where(created_by: current_user).order("name ASC")

    @sale_lists = SaleList.filter(params.slice(:debt, :customer_id, :product_id, :start_date, :end_date, :note))
    @sale_lists = @sale_lists.where(created_by: current_user.id).order(date: :desc).page(params[:page]).per(params[:limit])
  end

  def destroy
    SaleListBusinessType.where(sale_list_id: params[:id]).delete_all
    @sale_list.destroy
    respond_to do |format|
      format.html { redirect_to sale_lists_url, notice: 'Sale list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /sale_lists/1
  # GET /sale_lists/1.json
  def show
    @title = "Sale List Details"
  end

  def edit
    @title = "Adding Payment"
  end

  def add_images
    @title = "Adding Images"
  end

  # PATCH/PUT /sale_lists/1
  # PATCH/PUT /sale_lists/1.json
  def update
    @title = "Adding Payment"
    @first_payment = @sale_list.first_payment
    @second_payment = params.require(:sale_list).permit(:add_payment)[:add_payment].to_i
    @note = params.require(:sale_list).permit(:note)[:note]
    @total_payment = @first_payment + @second_payment
    debt = false
    total_price = SaleListBusinessType.where(sale_list_id: @sale_list.id, created_by: current_user.id).sum(:sale_price)
    remain_price = total_price - @sale_list.first_payment
    if remain_price > @second_payment
      debt = true
    end

    respond_to do |format|
      if @sale_list.update(first_payment: @total_payment, note: @note, debt: debt)
        format.html { redirect_to sale_lists_path, notice: 'Payment was successfully added.' }
        format.json { render :show, status: :ok, location: @sale_list }
      else
        format.html { render :add }
        format.json { render json: @sale_list.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_images
    @title = "Adding Images"
    respond_to do |format|
      if params[:image]
        @sale_list.avatars.attach(params[:image])
        format.html { redirect_to @sale_list, notice: 'Images was successfully added.' }
        format.json { render :show, status: :ok, location: @sale_list }
      else
        format.html { render :add }
        format.json { render json: @sale_list.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete_image_attachment
    @sale_list_id = params[:id].split('/')[0]
    @sale_list = SaleList.find(@sale_list_id)
    @image_id = params[:id].split('/')[1]
    @image = ActiveStorage::Attachment.find(@image_id)
    respond_to do |format|
      if @image.purge
        format.html { redirect_to @sale_list, notice: 'Images was successfully deleted.' }
        format.json { render :show, status: :ok, location: @sale_list }
      else
        format.html { render :show }
        format.json { render json: @sale_list.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_sale_list
      @sale_list = SaleList.find(params[:id])
    end
end

app/helpers/sale_lists_helper.rb
module SaleListsHelper
    def business_type_total_price(sale_list_id)
        @sale_products = SaleListBusinessType.where(sale_list_id: sale_list_id, created_by: current_user.id).sum(:sale_price)
    end

    def business_type_name(sale_list_id)
        @sale_products = SaleListBusinessType.where(sale_list_id: sale_list_id, created_by: current_user.id).select(:business_type_id).distinct
        @name = ""
        @sale_products.each do |sale_product|
            @business_type = BusinessType.find(sale_product[:business_type_id])
            @sale_products_count = SaleListBusinessType.where(sale_list_id: sale_list_id, business_type_id: sale_product[:business_type_id]).count

            if sale_product.equal?(@sale_products.last)
                @name+= @business_type.name + " (#{@sale_products_count})"
            else
                @name+= @business_type.name + " (#{@sale_products_count})" + ", "
            end
        end
        return @name
    end

    def sale_list_with_day(day)
        year = Date.current.year
        month = Date.current.month
        begin
            date = DateTime.parse("#{year}/#{month}/#{day}")
            SaleListBusinessType.where(created_by: current_user.id).joins(:sale_list).where(:sale_lists => { date: date..date.end_of_day }).sum(:sale_price)
        rescue ArgumentError
            0
        end
    end

    def sale_list_with_month(month, year)
        year = year == nil ? Date.current.year : year
        date = DateTime.parse("#{year}/#{month}/01")
        SaleListBusinessType.where(created_by: current_user.id).joins(:sale_list).where(:sale_lists => { date: date..date.end_of_month }).sum(:sale_price)
    end
end

app/views/sale_lists/_index_header.html.erb
<nav class="navbar navbar-index-header">
    <%= link_to '<i class="fas fa-print"></i>'.html_safe, print_sale_lists_print_path(debt: params[:debt] || '', customer_id: params[:customer_id] || '', product_id: params[:product_id] || '', start_date: params[:start_date] || '', end_date: params[:end_date] || ''), class: "btn btn-outline-info", target: "_blank" %>
    <%= form_tag sale_lists_path, method: "get", class: "form-inline" do %>
        <label> <%= check_box_tag 'debt', true, params[:debt], :onclick => 'this.form.submit()' %>  Accounts receivable &nbsp;</label>
        <%= select_tag "customer_id", options_from_collection_for_select(@customers, "id", "name", selected: params[:customer_id]), prompt: "Select a customer", class: "form-control mr-2 select2" %>
        <%= select_tag "product_id", options_from_collection_for_select(@products, "id", "name", selected: params[:product_id]), prompt: "Select a product", class: "form-control select2" %>
        <%= text_field_tag 'start_date', params[:start_date], class: 'form-control bg-white mr-2', data: { behavior: "flatpickr" }, placeholder: "Select start date" %>
        <%= text_field_tag 'end_date', params[:end_date], class: 'form-control bg-white mr-2', data: { behavior: "flatpickr" }, placeholder: "Select end date" %>
        <div class="input-group  mr-2">
            <%= text_field_tag :note, params[:note], placeholder: "note", class: "form-control" %>
            <div class="input-group-append">
                <%= button_tag(type: "submit", class: "btn btn-outline-secondary", id: "search-submit") do %>
                <i class="fas fa-search"></i>
                <% end %>
            </div>
        </div>
    <% end %>
</nav>

app/views/sale_lists/add_images.html.erb
<div class="row">
    <div class="col-md-8">
        <%= form_with(model: @sale_list, local: true) do |form| %>
            <div class="form-group">
                <%= form.label :image %>
                <%= form.file_field :image, multiple: true, class: "form-control" %>
            </div>

            <div class="actions">
                <%= form.submit "Add", class: "btn btn-info" %>
                <%= link_to 'Cancel', sale_lists_path, class: "btn btn-secondary" %>
            </div>
        <% end %>
    </div>
</div>

app/views/sale_lists/edit.html.erb
<table class="show-table mb-3">
  <tr>
    <th>Date:</th>
    <td><%= @sale_list.date.strftime("%d-%m-%Y %I:%M%P") %></td>
  </tr>
  <tr>
    <th>Customer Name:</th>
    <td><%= @sale_list.customer.name %></td>
  </tr>
  <tr>
    <th>Product Names:</th>
    <td><%= business_type_name(@sale_list.id) %></td>
  </tr>
  <tr>
    <th>Totle Price:</th>
    <td><%= business_type_total_price(@sale_list.id) %></td>
  </tr>
  <tr>
    <th>Payment:</th>
    <td><%= @sale_list.first_payment %></td>
  </tr>
  <tr>
    <th>Remain Price:</th>
    <td><%= business_type_total_price(@sale_list.id) - @sale_list.first_payment %></td>
  </tr>
</table>

<div class="row">
    <div class="col-md-8">
        <%= form_with(model: @sale_list, local: true) do |form| %>
            <div class="form-group">
                <%= form.label :payment %>
                <%= form.number_field :add_payment, step: :any, class: "form-control" %>
            </div>

            <div class="form-group">
                <%= form.label :note %>
                <%= form.text_area :note, class: "form-control" %>
            </div>

            <div class="actions">
                <%= form.submit "Add", class: "btn btn-info" %>
                <%= link_to 'Cancel', sale_lists_path, class: "btn btn-secondary" %>
            </div>
        <% end %>
    </div>
</div>

app/views/sale_lists/index.html.erb
<%= render 'index_header' %>
<div class="table-responsive">
  <table class="table table-striped mt-3">
    <thead class="text-white bg-secondary" id="print-header">
      <tr>
        <th>Date</th>
        <th>Customer Name</th>
        <th>Product Names</th>
        <th class="text-right">Total Price</th>
        <th class="text-right">Payment</th>
        <th class="text-right">Remain Price</th>
        <th>Note</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%
        @total_price = 0
        @first_payment = 0
        @remain_price = 0
      %>
      <% @sale_lists.each do |sale_list| %>
        <%
          @total_price += business_type_total_price(sale_list.id)
          @first_payment += sale_list.first_payment
          @remain_price += business_type_total_price(sale_list.id) - sale_list.first_payment
        %>
        <tr>
          <td><%= sale_list.date.strftime("%d-%m-%y %I:%M%P") %></td>
          <td><%= sale_list.customer.name %></td>
          <td><%= business_type_name(sale_list.id) %></td>
          <td class="text-right"><%= business_type_total_price(sale_list.id) %></td>
          <td class="text-right"><%= sale_list.first_payment %></td>
          <td class="text-right"><%= business_type_total_price(sale_list.id) - sale_list.first_payment %></td>
          <td><%= sale_list.note.length < 20 ? sale_list.note : sale_list.note[0..20] + "..." %></td>
          <td class="action">
            <%= link_to '<i class="fas fa-info-circle"></i>'.html_safe, sale_list, data: { toggle: 'tooltip', placement: 'bottom' }, title: t("action_button.detail") %>
            <%= link_to '<i class="fas fa-images"></i>'.html_safe, add_images_sale_list_path(sale_list), data: { toggle: 'tooltip', placement: 'bottom' }, title: t("action_button.add_image") %>
            <%= link_to '<i class="far fa-credit-card"></i>'.html_safe, edit_sale_list_path(sale_list), data: { toggle: 'tooltip', placement: 'bottom' }, title: t("action_button.add_payment") %>
            <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, sale_list, method: :delete, data: { confirm: 'Are you sure?', toggle: 'tooltip', placement: 'bottom' }, title: t("action_button.delete") %>
          </td>
        </tr>
      <% end %>
      <% if @sale_lists.count < 1 %>
        <tr>
          <td colspan="8" class="text-center">Empty Datas</td>
        </tr>
      <% else %>
        <tr class="bg-secondary text-white" id="print-footer">
          <td colspan="3" class="text-center">Total</td>
          <td class="text-right"><%= @total_price %></td>
          <td class="text-right"><%= @first_payment %></td>
          <td class="text-right"><%= @remain_price %></td>
          <td colspan="2" class="text-center"></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<nav class="navbar navbar-index-header">
  <%= form_tag sale_lists_path, method: :get do %>
    <%= select_tag :limit, options_for_select([25, 50, 100], selected: params[:limit]) %>
    <%= submit_tag "", :id => 'page-submit', :style => "display: none;" %>
    <label>records per page</label>
  <% end %>
  <%= paginate @sale_lists %>
</nav>

<script>
  $("#limit").change(function() {
    $("#page-submit").click();
  });
</script>

app/views/sale_lists/show.html.erb
<%= link_to '<i class="fas fa-cash-register"></i>'.html_safe, sale_lists_slip_path(@sale_list.id), class: "btn btn-outline-info", target: "_blank" %>
<table class="show-table mb-3">
  <tr>
    <th>Date:</th>
    <td><%= @sale_list.date.strftime("%d-%m-%Y %I:%M%P") %></td>
  </tr>
  <tr>
    <th>Customer Name:</th>
    <td><%= @sale_list.customer.name %></td>
  </tr>
  <tr>
    <th>Product Names:</th>
    <td><%= business_type_name(@sale_list.id) %></td>
  </tr>
  <tr>
    <th>Totle Price:</th>
    <td><%= business_type_total_price(@sale_list.id) %></td>
  </tr>
  <tr>
    <th>Payment:</th>
    <td><%= @sale_list.first_payment %></td>
  </tr>
  <tr>
    <th>Remain Price:</th>
    <td><%= business_type_total_price(@sale_list.id) - @sale_list.first_payment %></td>
  </tr>
  <tr>
    <th>Note:</th>
    <td><%= @sale_list.note %></td>
  </tr>
</table>
<div class="row mb-3">
  <div class="col-12 mb-3">
    <%= link_to 'Add Image', add_images_sale_list_path(@sale_list), class: "btn btn-outline-info" %>
  </div>
  <% if @sale_list.avatars.attached? %>
    <div class="col-12">
      <h4><u>Images</u></h3>
    </div>
    <% @sale_list.avatars.each do |image| %>
      <div class="col-md-3 col-lg-2 image-box">
        <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, delete_image_attachment_sale_list_url([@sale_list,image]), method: :delete, data: { confirm: 'Are you sure?', toggle: 'tooltip', placement: 'bottom' }, title: t("action_button.delete") %>
        <%= image_tag image, width: "100%" %>
      </div>
    <% end %>
  <% end %>
</div>

<%= link_to 'Edit', edit_sale_list_path(@sale_list), class: "btn btn-info" %>
<%= link_to 'Back', sale_lists_path, class: "btn btn-secondary" %>